name: deploy to server

on: push

jobs:
  first-jobs:
    runs-on: ubuntu-latest

    steps:
    - name: Hola Mundo
      run: echo "Hola Mundo"
  second-jobs:
    runs-on: ubuntu-latest

    steps:
    - name: Hola Mundo
      run: echo "Hola Mundo"
