name: deploy to server

on: push

jobs:

  first-jobs:
    runs-on: ubuntu-latest
    outputs:
      salida: ${{ steps.step_1.outputs.my_variable }} # esto es para que se pueda usar el resultado del primer job en el segundo job
    steps:
    - name: Crear archivo
      run: |
        echo "archivo_prueva, hola" >> test.log

    - name: subir artefacto
      uses: actions/upload-artifact@v4
      with:
        name: archivo_prueba
        path: test.log
