name: deploy to server

on: push

jobs:

  first-jobs:
    runs-on: ubuntu-latest

    steps:
    - name: Crear variable
      id: step_1
      run: echo "my_variable=Hola Mundo" >> $GITHUB_OUTPUT

    - name: Mostrar variable en el mismo job
      run: echo "${{ steps.step_1.outputs.my_variable }}"
  second-jobs:
    if: ${{ github.ref == 'refs/heads/main' }} # esto hace que se ejecute solo si se hace un push a la rama main (solo un if)
    needs: first-jobs # este hace que se ejecute después del primer job para que se pueda usar el resultado del primer job depende de este
    # si no se pone, se ejecuta en paralelo
    runs-on: ubuntu-latest

    steps:
    - name: Hola Mundo
      run: echo "hola mundo 2"
